### ISSUE TITLE
fiber return Signing succeeded: CkbTxUnlockError(TxDep(Other(invalid cell status: "unknown"))) panic

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/fiber#246]
env： dev node 
1. close channel
2. open channel many times
return CkbTxUnlockError(TxDep(Other(invalid cell status: "unknown")))
```

  2024-10-18T07:12:51.313559Z DEBUG fnn::fiber::network: Funding transaction broadcast result: Ok(TraceTxResponse { tx: Some(TransactionView { inner: Transaction { version: JsonUint(0), cell_deps: [CellDep { out_point: OutPoint { tx_hash: H256 ( [ 0xa6, 0x11, 0xf4, 0x19, 0x52, 0x57, 0x4b, 0x8a, 0x20, 0x04, 0x65, 0xb2, 0x28, 0x1d, 0x17, 0xbc, 0x11, 0x96, 0xa8, 0x78, 0xe3, 0x1f, 0x20, 0x68, 0x57, 0xee, 0x3d, 0x20, 0x92, 0x5d, 0x57, 0x95 ] ), index: JsonUint(0) }, dep_type: DepGroup }], header_deps: [], inputs: [CellInput { since: JsonUint(0), previous_output: OutPoint { tx_hash: H256 ( [ 0x99, 0x03, 0x4c, 0xdb, 0xf4, 0x4a, 0x1d, 0xe0, 0xc7, 0x91, 0x71, 0xdd, 0x8d, 0xb9, 0x45, 0x04, 0x49, 0xe6, 0x76, 0xd5, 0xb0, 0x84, 0xfa, 0xcf, 0xbe, 0xf0, 0xed, 0xf4, 0x80, 0xfd, 0xb7, 0x08 ] ), index: JsonUint(1) } }, CellInput { since: JsonUint(0), previous_output: OutPoint { tx_hash: H256 ( [ 0x99, 0x03, 0x4c, 0xdb, 0xf4, 0x4a, 0x1d, 0xe0, 0xc7, 0x91, 0x71, 0xdd, 0x8d, 0xb9, 0x45, 0x04, 0x49, 0xe6, 0x76, 0xd5, 0xb0, 0x84, 0xfa, 0xcf, 0xbe, 0xf0, 0xed, 0xf4, 0x80, 0xfd, 0xb7, 0x08 ] ), index: JsonUint(2) } }], outputs: [CellOutput { capacity: JsonUint(26200000000), lock: Script { code_hash: H256 ( [ 0x03, 0xae, 0x44, 0x5d, 0x1b, 0xec, 0x99, 0x30, 0xba, 0x5d, 0x9c, 0x77, 0xa0, 0xc2, 0x11, 0x0c, 0x0f, 0x7e, 0x5f, 0xa5, 0x04, 0xe7, 0x34, 0x3d, 0xc1, 0x3d, 0x9a, 0xaa, 0x86, 0x49, 0xcf, 0xcb ] ), hash_type: Data1, args: JsonBytes(b"\xa8\xd8\xcf\x1e\xfb\xa9Y\x14\xca5\xc2\x8b\x04S\x1b\xd0\xc1\xc0\x0b\xad") }, type_: None }, CellOutput { capacity: JsonUint(1999999959999998862), lock: Script { code_hash: H256 ( [ 0x9b, 0xd7, 0xe0, 0x6f, 0x3e, 0xcf, 0x4b, 0xe0, 0xf2, 0xfc, 0xd2, 0x18, 0x8b, 0x23, 0xf1, 0xb9, 0xfc, 0xc8, 0x8e, 0x5d, 0x4b, 0x65, 0xa8, 0x63, 0x7b, 0x17, 0x72, 0x3b, 0xbd, 0xa3, 0xcc, 0xe8 ] ), hash_type: Type, args: JsonBytes(b"\xc82\x8a\xab\xcd\x9b\x9e\x8ed\xfb\xc5f\xc48\\;\xde\xb2\x19\xd7") }, type_: None }, CellOutput { capacity: JsonUint(519873491299999298), lock: Script { code_hash: H256 ( [ 0x9b, 0xd7, 0xe0, 0x6f, 0x3e, 0xcf, 0x4b, 0xe0, 0xf2, 0xfc, 0xd2, 0x18, 0x8b, 0x23, 0xf1, 0xb9, 0xfc, 0xc8, 0x8e, 0x5d, 0x4b, 0x65, 0xa8, 0x63, 0x7b, 0x17, 0x72, 0x3b, 0xbd, 0xa3, 0xcc, 0xe8 ] ), hash_type: Type, args: JsonBytes(b"G\r\xcd\xc5\xe4@d\x90\x96P\x11:'K;6\xae\xcbm\xc7") }, type_: None }], outputs_data: [JsonBytes(b""), JsonBytes(b""), JsonBytes(b"")], witnesses: [JsonBytes(b"U\0\0\0\x10\0\0\0U\0\0\0U\0\0\0A\0\0\0\xe8AFc\xd4\x94\x9e\xff?\x15\xec\x05\xc2\x04\xee\xce\xda&A~\x0f4|\xfd\xa2\xc4Z\xab\xbd^\"i\x17\xf5\x0c\x82\x85\0\xe2k32@\x06-\xe7\xc9\xe4\x9f\x17K\x1b\xa3\x84H\xe6C\xd9\x82\xb1\x14X\xffu\x01"), JsonBytes(b"U\0\0\0\x10\0\0\0U\0\0\0U\0\0\0A\0\0\0]\xd4\x9ev#\xc8\xb1\x13-\xa5\xbb\xf6\xc8\xf3;=\x18\x97\xd0\xf6\xd35o\xad\x13\xa0\xd6INtg\x88\"\xb6\xc4\xf0<\x07B\xf5\xd0\\Q\xa5N\xfcK8\x879\xcd\x07\xd2 \xbc8\xff\xb0\x9b\xd5\xbbt\x8f\x90\0")] }, hash: H256 ( [ 0xb8, 0x0b, 0xae, 0x03, 0x4a, 0xfb, 0x4c, 0xbd, 0xcf, 0xe3, 0x57, 0x55, 0x8f, 0xe1, 0xb8, 0xe7, 0xf5, 0xf9, 0x01, 0x79, 0x4d, 0x8e, 0x59, 0xd8, 0xae, 0xe2, 0x28, 0x59, 0x7e, 0x82, 0x50, 0x53 ] ) }), status: TxStatus { status: Committed, block_number: Some(JsonUint(637)), block_hash: Some(H256 ( [ 0x02, 0x6d, 0xd8, 0x59, 0x35, 0xc8, 0x77, 0x3b, 0x69, 0xd5, 0xe1, 0x21, 0xf0, 0x65, 0xb0, 0x19, 0x73, 0x62, 0x89, 0x4f, 0x76, 0x57, 0xc1, 0x94, 0xd7, 0xeb, 0x88, 0x2f, 0x6b, 0x2e, 0x9f, 0x87 ] )), reason: None } })
    at src/fiber/network.rs:3085

  2024-10-18T07:12:51.314073Z  INFO fnn::fiber::network: Funding transaction Byte32(0xb80bae034afb4cbdcfe357558fe1b8e7f5f901794d8e59d8aee228597e825053) confirmed
    at src/fiber/network.rs:3096

thread 'tokio-runtime-worker' panicked at /Users/guopenglin/demo2/fiber2/fiber/src/fiber/network.rs:1377:26:
Signing succeeded: CkbTxUnlockError(TxDep(Other(invalid cell status: "unknown")))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
[node.log](https://github.com/user-attachments/files/17429857/node.log)

**Comment by contrun** [comment]
There could be two problems here.
- The first is that the `Sign` message of chain actor is obviously doing a little bit more than just signing the transaction https://github.com/contrun/fiber/blob/ab4203f9eb31fe5c21c5979beeb4ae12fd84c21d/src/ckb/funding/funding_tx.rs#L362-L392. Thus the assumption of `Sign` request never fails is false https://github.com/contrun/fiber/blob/ab4203f9eb31fe5c21c5979beeb4ae12fd84c21d/src/fiber/network.rs#L1436 .
- The second problem is that the `FundingTxBuilder` seems to be stateless, meaning that even if we've used some cell for a funding transaction, it is still possible for us to use the same transaction. This is exactly https://github.com/nervosnetwork/fiber/issues/74 . I don't know what is the newest status for that issue. Ping @doitian

**Comment by sunchengzhu** [comment]
I am also encountering this issue where I repeatedly send an `open_channel` request to a fiber node and wait for the channel to become `CHANNEL_READY` before sending the next request. This problem occurs frequently and significantly impacts my ability to establish channels in bulk. Could you please inform me when this issue is expected to be resolved? @contrun 

fnn version
[0804cb8](https://github.com/nervosnetwork/fiber/commit/0804cb82e7d50548819f4767f0112df48492aab3)

fnn log
```
thread 'tokio-runtime-worker' panicked at /Users/sunchengzhu/tmp/fiber/src/fiber/network.rs:1255:26:
Signing succeeded: CkbTxUnlockError(TxDep(Other(http error: `error sending request for url (https://testnet.ckbapp.dev/): error trying to connect: connection closed via error`

Caused by:
    0: error sending request for url (https://testnet.ckbapp.dev/): error trying to connect: connection closed via error
    1: error trying to connect: connection closed via error
    2: connection closed via error)))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This panic occurs right after sending the `open_channel` request.
```
channel-90 at 2025-01-20 01:54:56
{"jsonrpc":"2.0","result":{"temporary_channel_id":"0x5c9a9485c7d3eb92cae013e6b4b52c93dbf22b45266247a4add10ee85000192c"},"id":"1"}
curl: (7) Failed to connect to 127.0.0.1 port 8231 after 0 ms: Couldn't connect to server
Expected 90 channels on port 8231, but found . Retrying...
curl: (7) Failed to connect to 127.0.0.1 port 8231 after 0 ms: Couldn't connect to server
Expected 90 channels on port 8231, but found . Retrying...
```

**Comment by contrun** [comment]
@sunchengzhu This is a known unsolved problem. For the time being, we have not fixed this yet. We have to create channels one by one. @doitian Please update the issue when there is any progress.

**Comment by sunchengzhu** [comment]
> [@sunchengzhu](https://github.com/sunchengzhu) This is a known unsolved problem. For the time being, we have not fixed this yet. We have to create channels one by one. [@doitian](https://github.com/doitian) Please update the issue when there is any progress.

Thank you for your response. If I restart the fnn, it remains operational. Should I encounter this issue, I will restart it and continue using it.
