### ISSUE TITLE
[open channel] attempt to add with overflow panic

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/fiber#252]
funding_amount : 0xfffffffffffffffffffffffffffffff
```
curl --location 'http://127.0.0.1:8228' --header 'Content-Type: application/json' --data '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "open_channel",
    "params": [
        {
            "peer_id": "Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo",
            "funding_amount": "0xfffffffffffffffffffffffffffffff",
            "public": true
        }
    ]
}'
response:
{"jsonrpc": "2.0", "result": {"temporary_channel_id": "0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58"}, "id": 42}

```
log
```
  2024-10-19T07:08:21.278810Z DEBUG fnn::fiber::channel: Created OpenChannel message to PeerId(Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo): ChannelInitialization(OpenChannel { chain_hash: Hash256(0x0000000000000000000000000000000000000000000000000000000000000000), channel_id: Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58), funding_udt_type_script: None, funding_amount: 21267647932558653966460912958285513215, shutdown_script: Script(0x490000001000000030000000310000009bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce80114000000c8328aabcd9b9e8e64fbc566c4385c3bdeb219d7), reserved_ckb_amount: 6200000000, funding_fee_rate: 1000, commitment_fee_rate: 1000, max_tlc_value_in_flight: 340282366920938463463374607431768211455, max_tlc_number_in_flight: 30, min_tlc_value: 0, to_local_delay: LockTime(10), funding_pubkey: Pubkey(PublicKey(5315c157c8283261fc858145f571d875c5351fd4ca8df49fc58dfad746df29ae751b597eed1bccdd3295a79e3e3d574581b6c40cbce56304d372cc6ec18c420b)), revocation_basepoint: Pubkey(PublicKey(658b3377f769bdb4a7841d29b761f71b46d41df428d1e0d2b790108f6d1c8fe3edad3f8b66a72d6d1b65a8096ec0834e37e35e8c2dcd85dc27e45847993242ad)), payment_basepoint: Pubkey(PublicKey(aa2760f0a0d9eeae5d2a80a617c64dfc06f4325e0aa7063d065d745a5441f769cadd88a06068bee5c60f176d192ce1d29f7a68b0c468fe153292251bd4bcb723)), delayed_payment_basepoint: Pubkey(PublicKey(8954048d95c15d5c887bb6fc7c150303a71d822e264123a0431935d81002b19e071d4ad7a5d327f627d8b73944b98c3f4bedccc1236ad6bf4d769be3c9d4c17d)), tlc_basepoint: Pubkey(PublicKey(78fb0c044a6da1571d3e7746447f3869eb4fe417dd60bc2d3e7f3a4db4528b81affb0d88b2db705823b2c51b5674cd3a27315c39f5d7e80498595bf48ee44679)), first_per_commitment_point: Pubkey(PublicKey(60f2982630f947a1eb13b496b953507d9bd92d773fd2a3e5e53c81c8c4fc160bc7617e043c91cb1a55f2567cf7d699719391290d04fa242929ddbf4eed238f85)), second_per_commitment_point: Pubkey(PublicKey(1529ce28556fa8fbd1eb659a171804a0360132c2ac53e32517faec20e5aaae16e358f7eabe04f9c8305ca19fba90460b471b48fae7c2ccfb355a9f795599c41c)), channel_announcement_nonce: Some(PubNonce { R1: Point(03dfe88c583f523d972920a0170823e6013663b5053245b012ee404ad2f36bc614), R2: Point(03642880501b7f538aaf262c03d3fdd514a09828b7cdfe76e9a8e538e92fea0980) }), next_local_nonce: PubNonce { R1: Point(035c4ae08c4b1934161090c161e409a92f38f37c130a879ace88ec4cb72a3a7d40), R2: Point(033f082c494e19836f5615451517637f52dd610616bc32728f9f8a49b279a56287) }, channel_flags: ChannelFlags(PUBLIC) })
    at src/fiber/channel.rs:1541
    in ractor::actor::Actor with id: "0.5", name: "Channel-0 QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF <-> Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo"
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.278881Z DEBUG fnn::fiber::channel: Updating channel state from NegotiatingFunding(NegotiatingFundingFlags(0x0)) to NegotiatingFunding(NegotiatingFundingFlags(OUR_INIT_SENT))
    at src/fiber/channel.rs:2753
    in ractor::actor::Actor with id: "0.5", name: "Channel-0 QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF <-> Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo"
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.278895Z DEBUG fnn::fiber::channel: Channel to peer PeerId(Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo) with id Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58) created
    at src/fiber/channel.rs:1559
    in ractor::actor::Actor with id: "0.5", name: "Channel-0 QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF <-> Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo"
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.278998Z DEBUG fnn::fiber::network: Channel f0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58 created
    at src/fiber/network.rs:2934
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.279045Z DEBUG fnn::fiber::network: Handling command: SendFiberMessage(FiberMessageWithPeerId { peer_id: PeerId(Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo), message: ChannelInitialization(OpenChannel { chain_hash: Hash256(0x0000000000000000000000000000000000000000000000000000000000000000), channel_id: Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58), funding_udt_type_script: None, funding_amount: 21267647932558653966460912958285513215, shutdown_script: Script(0x490000001000000030000000310000009bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce80114000000c8328aabcd9b9e8e64fbc566c4385c3bdeb219d7), reserved_ckb_amount: 6200000000, funding_fee_rate: 1000, commitment_fee_rate: 1000, max_tlc_value_in_flight: 340282366920938463463374607431768211455, max_tlc_number_in_flight: 30, min_tlc_value: 0, to_local_delay: LockTime(10), funding_pubkey: Pubkey(PublicKey(5315c157c8283261fc858145f571d875c5351fd4ca8df49fc58dfad746df29ae751b597eed1bccdd3295a79e3e3d574581b6c40cbce56304d372cc6ec18c420b)), revocation_basepoint: Pubkey(PublicKey(658b3377f769bdb4a7841d29b761f71b46d41df428d1e0d2b790108f6d1c8fe3edad3f8b66a72d6d1b65a8096ec0834e37e35e8c2dcd85dc27e45847993242ad)), payment_basepoint: Pubkey(PublicKey(aa2760f0a0d9eeae5d2a80a617c64dfc06f4325e0aa7063d065d745a5441f769cadd88a06068bee5c60f176d192ce1d29f7a68b0c468fe153292251bd4bcb723)), delayed_payment_basepoint: Pubkey(PublicKey(8954048d95c15d5c887bb6fc7c150303a71d822e264123a0431935d81002b19e071d4ad7a5d327f627d8b73944b98c3f4bedccc1236ad6bf4d769be3c9d4c17d)), tlc_basepoint: Pubkey(PublicKey(78fb0c044a6da1571d3e7746447f3869eb4fe417dd60bc2d3e7f3a4db4528b81affb0d88b2db705823b2c51b5674cd3a27315c39f5d7e80498595bf48ee44679)), first_per_commitment_point: Pubkey(PublicKey(60f2982630f947a1eb13b496b953507d9bd92d773fd2a3e5e53c81c8c4fc160bc7617e043c91cb1a55f2567cf7d699719391290d04fa242929ddbf4eed238f85)), second_per_commitment_point: Pubkey(PublicKey(1529ce28556fa8fbd1eb659a171804a0360132c2ac53e32517faec20e5aaae16e358f7eabe04f9c8305ca19fba90460b471b48fae7c2ccfb355a9f795599c41c)), channel_announcement_nonce: Some(PubNonce { R1: Point(03dfe88c583f523d972920a0170823e6013663b5053245b012ee404ad2f36bc614), R2: Point(03642880501b7f538aaf262c03d3fdd514a09828b7cdfe76e9a8e538e92fea0980) }), next_local_nonce: PubNonce { R1: Point(035c4ae08c4b1934161090c161e409a92f38f37c130a879ace88ec4cb72a3a7d40), R2: Point(033f082c494e19836f5615451517637f52dd610616bc32728f9f8a49b279a56287) }, channel_flags: ChannelFlags(PUBLIC) }) })
    at src/fiber/network.rs:1197
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.279332Z DEBUG fnn::fiber::network: Handling event: NetworkServiceEvent(ChannelCreated(PeerId(Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo), Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58)))
    at src/fiber/network.rs:992
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.285902Z DEBUG fnn::fiber::network: Handling event: PeerMessage(PeerId(Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo), ChannelNormalOperation(AcceptChannel(AcceptChannel { channel_id: Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58), funding_amount: 0, reserved_ckb_amount: 6200000000, max_tlc_value_in_flight: 340282366920938463463374607431768211455, max_tlc_number_in_flight: 30, min_tlc_value: 0, to_local_delay: LockTime(10), funding_pubkey: Pubkey(PublicKey(308ec760912f56f66157f07ff3a2eac9450927a4f10ee59f751194f027fa854bc67566cf9dfd4aeae5211e086c305a830ab1f56200a7016d3c00ca3c85f92ce0)), shutdown_script: Script(0x490000001000000030000000310000009bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce80114000000470dcdc5e44064909650113a274b3b36aecb6dc7), revocation_basepoint: Pubkey(PublicKey(4ef949ebc733d862c058ff70e5c01bbed4be5f94fbca07ccb4bd1e5bb9394178b7450c9b6d64bee45d121ffd67718eca41522b62318320d9da77df0e374ad4a7)), payment_basepoint: Pubkey(PublicKey(e22ab6f6dc97260157beb8a5fd1440298dffcc2446e0cb1f2a65e7a601453be0206aea2a1694838e1e1272f4c894414567cbb55077c2720a069e520b53bd16aa)), delayed_payment_basepoint: Pubkey(PublicKey(e23286ed73a6cb2fe060bc5f7508a125d5a623747ca8a30eb673e20d6243eb692e9380814be6f1ebdf4bc6c5dfcbea820d62160748571778b195b7d5cd1ebd80)), tlc_basepoint: Pubkey(PublicKey(5449728f4e22a35aa469fcf0b2fcc6425c5c1a3233c1c196f9e84156692dab91cc41c5c68a074393afe6adb04f8c8b89513550fe36f56f447bcfba3bc2e4fb22)), first_per_commitment_point: Pubkey(PublicKey(b7284e603336ef1fad9f514228a936d7ad4e7c7451a802af55fbb1227523fd411ce7a358bdef42006478839af14554b92e005b3a0b04ba5655f83bc4c409e336)), second_per_commitment_point: Pubkey(PublicKey(2d64485d285505b6937bdbd37bc95cae606c0f7be7300884f15c618a8339aeb5e2bacedc52e61ec10c91ebb6311c6e403eac61236af47b92584bc13205b85ff3)), channel_announcement_nonce: Some(PubNonce { R1: Point(03914e4f3748f170d6ecb14ce42481d444b794451ee74babfd88e0d0d6ad1a9144), R2: Point(02f3d69d54436cf42bf8a6f2eb932dd3315ebee0a073a871710acafe205e2750a8) }), next_local_nonce: PubNonce { R1: Point(02238ae1f07b8f831bb54241700b0d0dae5e57a3fedef2f079ed9a60483ccf11e6), R2: Point(02de3a86379d6327a86d323b24e88471d570ecbf4f8f6e1dd1d96822bb11fc144f) } })))
    at src/fiber/network.rs:992
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.286877Z DEBUG fnn::fiber::channel: Updating channel state from NegotiatingFunding(NegotiatingFundingFlags(OUR_INIT_SENT)) to NegotiatingFunding(NegotiatingFundingFlags(OUR_INIT_SENT | THEIR_INIT_SENT))
    at src/fiber/channel.rs:2753
    in ractor::actor::Actor with id: "0.5", name: "Channel-0 QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF <-> Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo"

  2024-10-19T07:08:21.287056Z DEBUG fnn::fiber::channel: Updating remote channel announcement nonce: PubNonce { R1: Point(03914e4f3748f170d6ecb14ce42481d444b794451ee74babfd88e0d0d6ad1a9144), R2: Point(02f3d69d54436cf42bf8a6f2eb932dd3315ebee0a073a871710acafe205e2750a8) }
    at src/fiber/channel.rs:3986
    in ractor::actor::Actor with id: "0.5", name: "Channel-0 QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF <-> Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo"

  2024-10-19T07:08:21.287099Z DEBUG fnn::fiber::channel: Successfully processed AcceptChannel message AcceptChannel { channel_id: Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58), funding_amount: 0, reserved_ckb_amount: 6200000000, max_tlc_value_in_flight: 340282366920938463463374607431768211455, max_tlc_number_in_flight: 30, min_tlc_value: 0, to_local_delay: LockTime(10), funding_pubkey: Pubkey(PublicKey(308ec760912f56f66157f07ff3a2eac9450927a4f10ee59f751194f027fa854bc67566cf9dfd4aeae5211e086c305a830ab1f56200a7016d3c00ca3c85f92ce0)), shutdown_script: Script(0x490000001000000030000000310000009bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce80114000000470dcdc5e44064909650113a274b3b36aecb6dc7), revocation_basepoint: Pubkey(PublicKey(4ef949ebc733d862c058ff70e5c01bbed4be5f94fbca07ccb4bd1e5bb9394178b7450c9b6d64bee45d121ffd67718eca41522b62318320d9da77df0e374ad4a7)), payment_basepoint: Pubkey(PublicKey(e22ab6f6dc97260157beb8a5fd1440298dffcc2446e0cb1f2a65e7a601453be0206aea2a1694838e1e1272f4c894414567cbb55077c2720a069e520b53bd16aa)), delayed_payment_basepoint: Pubkey(PublicKey(e23286ed73a6cb2fe060bc5f7508a125d5a623747ca8a30eb673e20d6243eb692e9380814be6f1ebdf4bc6c5dfcbea820d62160748571778b195b7d5cd1ebd80)), tlc_basepoint: Pubkey(PublicKey(5449728f4e22a35aa469fcf0b2fcc6425c5c1a3233c1c196f9e84156692dab91cc41c5c68a074393afe6adb04f8c8b89513550fe36f56f447bcfba3bc2e4fb22)), first_per_commitment_point: Pubkey(PublicKey(b7284e603336ef1fad9f514228a936d7ad4e7c7451a802af55fbb1227523fd411ce7a358bdef42006478839af14554b92e005b3a0b04ba5655f83bc4c409e336)), second_per_commitment_point: Pubkey(PublicKey(2d64485d285505b6937bdbd37bc95cae606c0f7be7300884f15c618a8339aeb5e2bacedc52e61ec10c91ebb6311c6e403eac61236af47b92584bc13205b85ff3)), channel_announcement_nonce: Some(PubNonce { R1: Point(03914e4f3748f170d6ecb14ce42481d444b794451ee74babfd88e0d0d6ad1a9144), R2: Point(02f3d69d54436cf42bf8a6f2eb932dd3315ebee0a073a871710acafe205e2750a8) }), next_local_nonce: PubNonce { R1: Point(02238ae1f07b8f831bb54241700b0d0dae5e57a3fedef2f079ed9a60483ccf11e6), R2: Point(02de3a86379d6327a86d323b24e88471d570ecbf4f8f6e1dd1d96822bb11fc144f) } }
    at src/fiber/channel.rs:3997
    in ractor::actor::Actor with id: "0.5", name: "Channel-0 QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF <-> Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo"

  2024-10-19T07:08:21.287574Z DEBUG fnn::fiber::channel: Channel Id changed from Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58) to Hash256(0xabfab56da2b4ce598040bf63b70d32722a6bf1945beb48e129cc4dce67c0b953)
    at src/fiber/channel.rs:4780
    in ractor::actor::Actor with id: "0.5", name: "Channel-0 QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF <-> Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo"

  2024-10-19T07:08:21.289291Z DEBUG fnn::fiber::network: Handling event: ChannelAccepted(PeerId(Qmai8nVGMooBv3WcspFKvQwjUKDXwu11PGQEfLbELMuJSo), Hash256(0xabfab56da2b4ce598040bf63b70d32722a6bf1945beb48e129cc4dce67c0b953), Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58), 21267647932558653966460912958285513215, 0, Script(0x4900000010000000300000003100000003ae445d1bec9930ba5d9c77a0c2110c0f7e5fa504e7343dc13d9aaa8649cfcb0214000000b43a78db5233cde12ac4deddf55f6cd7befbb3c4), None, 6200000000, 6200000000, 1000)
    at src/fiber/network.rs:992
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.289325Z DEBUG fnn::fiber::network: Channel accepted: Hash256(0xf0f77ccdc459759411e2141e35691b6f7e098fd6403ec126752afcfc59965d58) -> Hash256(0xabfab56da2b4ce598040bf63b70d32722a6bf1945beb48e129cc4dce67c0b953)
    at src/fiber/network.rs:1056
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.289344Z DEBUG fnn::fiber::network: Starting funding channel
    at src/fiber/network.rs:1063
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.289360Z DEBUG fnn::fiber::network: Handling command: UpdateChannelFunding(Hash256(0xabfab56da2b4ce598040bf63b70d32722a6bf1945beb48e129cc4dce67c0b953), Transaction(0x440000000c00000040000000340000001c0000002000000024000000280000002c0000003000000000000000000000000000000000000000040000000400000004000000), FundingRequest { script: Script(0x4900000010000000300000003100000003ae445d1bec9930ba5d9c77a0c2110c0f7e5fa504e7343dc13d9aaa8649cfcb0214000000b43a78db5233cde12ac4deddf55f6cd7befbb3c4), udt_type_script: None, local_amount: 18446744067509551615, funding_fee_rate: 1000, remote_amount: 0, local_reserved_ckb_amount: 6200000000, remote_reserved_ckb_amount: 6200000000 })
    at src/fiber/network.rs:1197
    in ractor::actor::Actor with id: "0.2", name: "Network QmQjwEbSyEkoBScbBE5k5UrP2bHmmHc1ARjkt1hgcB3MUF"

  2024-10-19T07:08:21.290245Z DEBUG fnn::ckb::funding::funding_tx: request.funding_fee_rate: 1000
    at src/ckb/funding/funding_tx.rs:295
    in ractor::actor::Actor with id: "0.1", name: "ckb"

  2024-10-19T07:08:21.365479Z DEBUG fnn::ckb::funding::funding_tx: build_funding_cell debug ckb_output: CellOutput(0x61000000100000001800000061000000ffffffffffffffff4900000010000000300000003100000003ae445d1bec9930ba5d9c77a0c2110c0f7e5fa504e7343dc13d9aaa8649cfcb0214000000b43a78db5233cde12ac4deddf55f6cd7befbb3c4)
    at src/ckb/funding/funding_tx.rs:195
    in ractor::actor::Actor with id: "0.1", name: "ckb"

thread 'tokio-runtime-worker' panicked at /Users/guopenglin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ckb-sdk-3.4.0/src/tx_builder/mod.rs:869:38:
attempt to add with overflow

```
[node.log](https://github.com/user-attachments/files/17443812/node.log)

expected: rpc return err

**Comment by chenyukang** [comment]
the root cause is in ckb-rust-sdk, I just open an PR for it: https://github.com/nervosnetwork/ckb-sdk-rust/pull/129

maybe we can also add more check in building funding tx.

**Comment by quake** [comment]
https://github.com/nervosnetwork/fiber/pull/255
