### ISSUE TITLE
[send_payment] Failed to send Seal

### ISSUE THREAD

**Issue by mfuuzy** [nervosnetwork/fiber#386]
"commit_hash": "feefe59"

I successfully created two Seal channels: A > B and B > A. A can create an invoice and B can pay it successfully, but when B creates an invoice, A fails to pay. The error is as follows:

```

  2024-12-11T10:05:21.117209Z ERROR fnn::fiber::network: Failed to send payment: SendPaymentError("Failed to build route, PathFind error: no path found")
    at src/fiber/network.rs:1596
    in ractor::actor::Actor with id: "0.2", name: "Network Qma6a38bXTddkkkrboEWCByvXnQvbzysfJSJCcFmWg28Fw"

  2024-12-11T10:05:21.117237Z ERROR fnn::rpc::channel: channel request params SendPaymentCommandParams { target_pubkey: None, amount: None, payment_hash: None, final_htlc_expiry_delta: None, invoice: Some("fibt10000000000001plcqluqnfjzgfw0pmm6vkvgwhrlvz0s8j3zynvpcjpld6phvxwf7w6g3msgcxux9p2hp56tutyyfc823q2mrpeq5w2tp95hrzq2f29tgc7hnupa60w2pzkdj02lmak85z7p5u2d0d63stc86et3qqaj927up4jp80u2pk43j347nfmmrgj6zter02vycl4qhhvf4phkql7kc9efs6myv0c3un8uecmh4w2kghsdmcu8k2jtjy0z2zd0mr4ert36cgq5esn3tufq436w7kg244a7d3zexnznaa4mf944qnhc86t76j065pnsdv0g8hh60c0chqea64pma5e323vq5qfw6vjz2966w6cz0cxy3nf67qkfe3xwj7mhz94n7qunafrn9ksmuqpjzqj0dmwyad7mlcf8qvyg7zm23vfw3h6j5nyvsmd32asdlns4qpj8d0s9"), timeout: None, max_fee_amount: None, max_parts: None, keysend: None, udt_type_script: None, allow_self_payment: None } => error: "Send payment error: Failed to build route, PathFind error: no path found"
    at src/rpc/channel.rs:633
```

Then I tried to cancel the problematic channel, but both A and B unexpectedly terminated. The error is as follows:
```
  2024-12-11T10:11:15.684789Z  INFO fnn::fiber::network: send command to channel: ChannelCommandWithId { channel_id: Hash256(0xde4740cc80d5543abc57c56d110f07a7e8d29403a57fc64ad7beab8744bf06c9), command: Shutdown(ShutdownCommand { close_script: Script(0x5500000010000000300000003100000025c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb0120000000122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936), fee_rate: FeeRate(1009), force: false }, RpcReplyPort { port: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) }, timeout: None }) }
    at src/fiber/network.rs:1385
    in ractor::actor::Actor with id: "0.2", name: "Network QmSoRjBerHayg5duYLW8yBb8SDSLxoxPiruAC9EEUkhYCf"

thread 'tokio-runtime-worker' panicked at src/fiber/channel.rs:4207:17:
assertion `left == right` failed
  left: 779
 right: 767
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by quake** [comment]
I think the closing bug has been resolved by https://github.com/nervosnetwork/fiber/pull/340, could you try it with current main branch?

**Comment by mfuuzy** [comment]
I am running Fiber using containers. After the unexpected restart just now, I found that A and B can successfully send to each other.

**Comment by mfuuzy** [comment]
channels info
```
{
				"channel_id": "0xa67fd1ef36c05e413ccca551eca7b9bd90df384101c7d0723eb37387733c58b4",
				"is_public": true,
				"channel_outpoint": "0x6587701a39c51035a90cc1f549e30096e550e235ca820e00613294989581cca400000000",
				"peer_id": "Qma6a38bXTddkkkrboEWCByvXnQvbzysfJSJCcFmWg28Fw",
				"funding_udt_type_script": {
					"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
					"hash_type": "type",
					"args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"
				},
				"state": {
					"state_name": "CHANNEL_READY",
					"state_flags": []
				},
				"local_balance": "0x1d1a94a2000",
				"offered_tlc_balance": "0x0",
				"remote_balance": "0x746a5288000",
				"received_tlc_balance": "0x0",
				"created_at": "0x193b54f113b"
			},
			{
				"channel_id": "0xbcee31bc70d46035467bfd792bc3cd62f21f250973a63f0d34b76c62634620ae",
				"is_public": true,
				"channel_outpoint": "0xdff996d5023969ffb3afdbdb3d3b4337ca30b663dab8ff0f2444402958aad03600000000",
				"peer_id": "Qma6a38bXTddkkkrboEWCByvXnQvbzysfJSJCcFmWg28Fw",
				"funding_udt_type_script": {
					"code_hash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
					"hash_type": "type",
					"args": "0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936"
				},
				"state": {
					"state_name": "CHANNEL_READY",
					"state_flags": []
				},
				"local_balance": "0x9184e72a000",
				"offered_tlc_balance": "0x0",
				"remote_balance": "0x0",
				"received_tlc_balance": "0x0",
				"created_at": "0x193b5229aa6"
			},
```

I recreated the channel and wanted to test if the new channel could be used. I tried sending again, but it prompted that the local_balance was insufficient. It seems it didn’t route through another channel with sufficient local_balance.

```
  2024-12-11T10:56:57.668085Z ERROR fnn::fiber::channel: Error while processing channel command: InvalidParameter("Adding tlc Offered(0) with amount 5000000000000 exceeds local balance 2000000000000")
    at src/fiber/channel.rs:1860
    in ractor::actor::Actor with id: "0.14"

  2024-12-11T10:56:57.668272Z ERROR fnn::fiber::network: Failed to send payment: SendPaymentError("Failed to send onion packet with error IncorrectOrUnknownPaymentDetails")
    at src/fiber/network.rs:1596
    in ractor::actor::Actor with id: "0.2", name: "Network QmSoRjBerHayg5duYLW8yBb8SDSLxoxPiruAC9EEUkhYCf"

  2024-12-11T10:56:57.668303Z ERROR fnn::rpc::channel: channel request params SendPaymentCommandParams { target_pubkey: None, amount: None, payment_hash: None, final_htlc_expiry_delta: None, invoice: Some("fibt50000000000001plcqluqnfjzgfw0pmm6vkwpj8emxataxp36rsfpeu3hf6l83rr66c9jlueaupejnk4mjgf6vdduw5s89lgajm5qtz23khvshgepc4290sg95k7key5kpl94yr99lqanxe4fvhjq4kvh2fkl8300uqn3s59desvwhft3p98f6k0juuyud42u0x35dq46gx2afjqw2xrj95v3xz7fr9w82uhs283uxjvtr8aelfadzm7kkk8mg3g7wymxwvwsacmalrdak5mfscqg75qrkqxm26hst3xs3dzkms7g3fjt6j4p6dk7wtvn04w75rnstp048afuqd988ylqzvp9c7gd2qp68mxtppk8qe4wm3m26uccd5ahh9kcn5254jeqytt52jwc6wv9a4r9qzxvjp43tkk8ftutc20czay42m2uvlnak4jenr5xemw9flmjgp3n7p53"), timeout: None, max_fee_amount: None, max_parts: None, keysend: None, udt_type_script: None, allow_self_payment: None } => error: "Send payment error: Failed to send onion packet with error IncorrectOrUnknownPaymentDetails"
    at src/rpc/channel.rs:633
```

**Comment by chenyukang** [comment]
This is a good test case pointed out error handling didn't recover well.
The error returned here:

https://github.com/nervosnetwork/fiber/blob/10ee9252c529c1638513dd65804c91db1ed3c4fc/src/fiber/channel.rs#L4145-L4150

`InvalidParameter` is matched with `IncorrectOrUnknownPaymentDetails`, it's not right. We should match balance error into a temporary channel failure, and then trigger another round of path finding and payment sending, I will fix this scenario. 

Thanks for reporting.
